//example
export const ADD_COUNT = 'ADD_COUNT';

export const INVOKE_LOGIN = 'INVOKE_LOGIN';
export const INVOKE_FAILED_LOGIN = 'INVOKE_FAILED_LOGIN';

export const INVOKE_SIGNUP = 'INVOKE_SIGNUP';
export const INVOKE_FAILED_SIGNUP = 'INVOKE_FAILED_SIGNUP';

export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_EVENTS_FAILED = 'RECEIVE_EVENTS_FAILED';
export const CHANGE_CURR_EVENT = 'CHANGE_CURR_EVENT';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';